---
title: "Data Completeness Report (Beta)"
author: "Martin Frigaard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: flatly
    source_code: embed

runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(reactable)
library(flexdashboard)
library(readxl)
library(htmltools)
library(noteMD)
library(knitr)
```

```{r FieldsListing}
FieldsListing <- read_excel("data/Fields_DataCompleteness_270302_20210110.xlsx", 
    sheet = "Fields Listing")

RemovedListing <- read_excel("data/Fields_DataCompleteness_270302_20210110.xlsx", 
    sheet = "Removed Listing")
# FieldsListing %>% glimpse()
```

Data Completeness Listing
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### Download report 


```{r downloadButton-describe_download}
downloadButton(
  outputId = "describe_download",
  label = "Download Report",
  class = "butt"
)
```

```{r downloadHandler}
downloadHandler(

  # **create file name** ----
  filename = function() {
    paste("Summary", Sys.Date(), switch(
      input$format, PDF = ".pdf", Word = ".docx"
    ), sep = "")
  },
  # **(PDF) create content** ----
  content = function(file) {
    if (input$format == "PDF") {

      # **(PDF) start of progressing indicator** ----
      withProgress(
        message = "Download in progress",
        detail = "This may take a while...",
        value = 0,
        {
          for (i in 1:15) {
            incProgress(1 / 15)
            Sys.sleep(0.01)
          }
          # **(PDF) end of progression** ----

          src <- normalizePath("summary_report.Rmd")
          # temporarily switch to the temp dir, in case you do not have write
          # permission to the current working directory
          owd <- setwd(tempdir())
          on.exit(setwd(owd))

          file.copy(src, "summary_report.Rmd", overwrite = TRUE)

          library(rmarkdown)
          out <- render("summary_report.Rmd", pdf_document())
          file.rename(out, file)
        }
      )
      # **end of pdf content** ----
    } else {
      # **(DOCX) create content** ----
      # **(DOCX) start of progressing indicator** ----
      withProgress(
        message = "Download in progress",
        detail = "This may take a while...",
        value = 0,
        {
          for (i in 1:15) {
            # incremental progress
            incProgress(1 / 15)
            # set the Sys.sleep time
            Sys.sleep(0.01)
          }
          # (DOCX) end of progression ----

          src <- normalizePath("summary_report_word.Rmd")
          # temporarily switch to the temp dir, in case you do not have write
          # permission to the current working directory
          owd <- setwd(tempdir())
          on.exit(setwd(owd))
          file.copy(src, "summary_report_word.Rmd", overwrite = TRUE)

          library(rmarkdown)
          out <- render("summary_report_word.Rmd", word_document())
          file.rename(out, file)
        }
      )
    }
  }
)
```


```{r radioButtons-format}
radioButtons(
  inputId = "format",
  label = "Document format",
  choices = c("PDF", "Word"),
  inline = TRUE
)
```


Row 
-----------------------------------------------------------------------

### Fields Listing

```{r FieldsListing-data}
renderReactable({
reactable(FieldsListing, 
          resizable = TRUE, 
          showPageSizeOptions = TRUE, 
          onClick = "expand", 
          highlight = TRUE, 
          filterable = TRUE, 
          minRows = 50)
})
```

```{r helpText-tags-textarea-id-markdowninput_table_1}
# helpTex = Note... 
helpText("Note: make some comments about table 1...")
# textarea id (use markdowninput prefix!) 
tags$textarea(
  "Please use **markdown** syntax!",
  id    = "markdowninput_table_1",
  rows  = 3,
  style = "width:100%;"
)
```

```{r helpText-htmlOutput-outputId-markdowninput_table_1}
# helpText = Preview 
helpText("Preview:")
# htmlOutput = use htmlmarkdown prefix!
htmlOutput(outputId = "markdowninput_table_1")
```


Removed Listing
=======================================================================

Row
-----------------------------------------------------------------------

### Removed Listing

```{r RemovedListing-data}
renderReactable({
reactable(RemovedListing, 
          resizable = TRUE, 
          showPageSizeOptions = TRUE, 
          onClick = "expand", 
          highlight = TRUE, 
          filterable = TRUE, 
          minRows = 50)
})
```

```{r helpText-tags-textarea-id-markdowninput_table_2}
# helpTex = Note... 
helpText("Note: make some comments about table 2...")
# textarea id (use markdowninput prefix!) 
tags$textarea(
  "Please use **markdown** syntax!",
  id    = "markdowninput_table_2",
  rows  = 3,
  style = "width:100%;"
)
```

```{r helpText-htmlOutput-outputId-markdowninput_table_2}
# helpText = Preview 
helpText("Preview:")
# htmlOutput = use htmlmarkdown prefix!
htmlOutput(outputId = "markdowninput_table_2")
```



